Add apply_meta_as_tags macro
Montreal-Analytics/dbt-snowflake-utils pull request #21
Opened 2022-10-25 09:40 UTC by jamesweakley

This PR adds the apply_meta_as_tags as discussed here: https://github.com/dbt-labs/dbt-snowflake/issues/104

Documentation is available in the readme, I opted for a yaml-driven approach.

Tested on a sample model with dbt 1.3.0.

2022-10-25 19:18 UTC, MartinGuindon commented
Thank you for your contribution @jamesweakley. I will aim to merge this in the next few days!

2022-10-28 20:40 UTC, gmatsonANSYS commented
@jamesweakley I tested your macro using the yaml driven approach and the macro only executes if a table and column tag are set on a model. Are you able to have tags created/set using only the column meta tags?

the log file shows  " meta': {'database_tags': None}, 'transient': False}" and skips

2022-10-30 20:45 UTC, jamesweakley commented
@gmatsonANSYS good pickup, I hadn't tried that scenario. Will take a look today

2022-10-30 21:40 UTC, jamesweakley commented
@gmatsonANSYS it should now work even if you've only defined column tags

2022-10-31 17:23 UTC, gmatsonANSYS commented
Thanks James, the updates worked as expected. The only tweaks I had to make were around the existing tag filters:

Converted the table and column name to upper similar like the tag_name pipe to return matches.
`{%- set existing_tag_for_table = existing_tags|selectattr('0','equalto','TABLE')|selectattr('1','equalto',table_name|upper)|selectattr('3','equalto',tag_name|upper)|list -%}`

Updated to the fifth column index for the tag value comparison
`{% if existing_tag_for_table|length > 0 and existing_tag_for_table[0][4]==desired_tag_value %}`

2022-10-31 22:53 UTC, jamesweakley commented
@gmatsonANSYS thanks for the code snippets, I've pushed some more changes and tested various matching/non-matching scenarios and it seems consistent now

2022-11-08 10:40 UTC, jamesweakley commented
@gmatsonANSYS hopefully this all works in your test scenario now?

2022-11-08 13:07 UTC, gmatsonANSYS commented
@jamesweakley  runs smooth as silk. Thank you!

2022-11-08 14:16 UTC, MartinGuindon commented
Awesome, if there are no further updates to this PR I'll be merging it shortly.

2022-11-09 20:04 UTC, MartinGuindon requested changes
@jamesweakley The macro should be documented in macros.yml, and there's a typo in the README. Other than that, looks pretty good to me . Once fixed I'll merge and issue a new version.

2022-11-09 20:04 UTC, MartinGuindon commented on README.md
> +schema.yma
I assume this should be `# schema.yml`?

2022-11-09 21:38 UTC, jamesweakley commented
@MartinGuindon Thanks, I've pushed those changes now

2022-11-09 21:46 UTC, MartinGuindon approved these changes

2022-11-09 21:46 UTC, merged